@baseUrl = https://6128855786a213001729f948.mockapi.io/api/v1

POST {{baseUrl}}/login
content-type: application/json

{
    "email": "john@gmail.com",
    "password": "12345678"
}
###
GET {{baseUrl}}/logout
content-type: application/json